### ISSUE TITLE
[FixInsight Warning] _uProfilerManager.pas(1069): W504 Missing INHERITED call in destructor

### ISSUE THREAD

**Issue by IL2** [andremussche/asmprofiler#1]
In the code:
https://github.com/andremussche/asmprofiler/blob/master/Source/SRC/_uProfilerManager.pas#L1069
`destructor TProfileRun.Destroy;`
**[FixInsight Warning] _uProfilerManager.pas(1069): W504 Missing INHERITED call in destructor**
perhaps inherited call is missing because parent class destructor (TComponent.Destroy) is defined.

**Comment by andremussche** [comment]
Fixed:
https://github.com/andremussche/asmprofiler/blob/master/Source/SRC/_uProfilerManager.pas#L1082
